# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "14a5995ae8634749338e21b9bd9f20a9"
name = "Gemist"
application_url = "https://gemistapp.zooq.app"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://gemistapp.zooq.app/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
